### PR TITLE
Updated for december changes

### PR DESCRIPTION
**Pull request by ParaSpl01t**
Google search rolled out new design this december.
The change include a new js based height transition and same old suggestion list.

### CODE REVIEW

**Comment by andy9775** [comment]
Hey, thanks for the PR! Give me a few days (I'm currently in the middle of a few things) and if it looks good I'll merge it in.

**Comment by andy9775** [comment]
@ParaSpl01t it looks like `IsZvec` is a common class for the search result. I think it would make sense to query based on that rather than starting from `g`.

**Comment by ParaSpl01t** [comment]
@andy9775 Using className does make sense. However, It will only take one change by Google to completely rebuild the entire css bundle. That may possibly rename all the classes. 

Do we have any info on the css bundler google uses and weather classNames can survive minor changes in google's css?

Also, While looking for className for `.g > div > div:nth-child(2)` (for disabling automatic height adjustment) I noticed that this selector is no longer required, and automatic height adjustment does not happen when the suggestion are hidden. Should we remove the selector?

**Comment by andy9775** [comment]
I think you can make the same argument for using ‘g’ as a class name as well. Also, the n-th child selectors on line 18 could break if a div is added in the wrong spot. The current implementation has been going strong with no issues for 4 years as well.

My issue is, g seems a bit generic and could potentially catch things we don’t want and disable useful functionality.

**Comment by ParaSpl01t** [comment]
> My issue is, g seems a bit generic and could potentially catch things we don’t want and disable useful functionality.

That's a fair point. 

I'll update the PR. Btw, do we still need to keep the old code (line 1 - 10) for the locations where new change has not been rolled out yet?

**Comment by andy9775** [comment]
Let’s keep the old line. I know someone who revived the update before me so there may be others still not updated.

**Pull request merged**
